# connectorService.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: searchengine
  name: searchengine
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 80
    - port: 8443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app: searchengine
    component: python-app
  type: LoadBalancer