# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: connector-api
  labels:
    app: connector
    component: netcore-app
spec:
  containers:
    - image: smarthack2020acr.azurecr.io/connectorapi
      name: connector-api
      ports:
        - containerPort: 80
        - containerPort: 443